db.restaurants.find()
db.restaurants.find({}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({}, { _id: 0, restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({}, { _id: 0, restaurant_id: 1, name: 1, borough: 1, "address.zipcode": 1 })
db.restaurants.find({ borough: "Bronx" })
db.restaurants.find({ borough: "Bronx" }).limit(5)
db.restaurants.find({ borough: "Bronx" }).skip(5).limit(5)
db.restaurants.find({ "grades.score": { $gt: 90 }})
db.restaurants.find({$and:[{ "grades.score": {$gt:80} }, { "grades.score": {$lt:100} }]}) 
db.restaurants.find({ "address.coord.0": { $lt: -95.754168 } })
db.restaurants.find({ $and: [{ cuisine: { $ne: "American" } }, { "grades.score": { $gt: 70 } }, { "address.coord.1": { $lt: -65.754168 } }]})
db.restaurants.find({ cuisine: { $ne: "American" }, "grades.score": { $gt: 70 }, "address.coord.1": { $lt: -65.754168 }})
db.restaurants.find({ cuisine: { $ne: "American" }, "grades.grade": "A", borough: { $ne: "Brooklyn" }}).sort({ cuisine: -1 })
db.restaurants.find({ name: /^Wil/ }, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ name: /ces$/ }, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ name: /Reg/ }, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ $and: [{ $or: [{ cuisine: "American" }, { cuisine: "Chinese" }] }, { borough: "Bronx" }]})
db.restaurants.find({ borough: { $in: ["Staten Island", "Queens", "Bronx", "Brooklyn"] } }, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ borough: { $nin: ["Staten Island", "Queens", "Bronx", "Brooklyn"] } },  { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ "grades.score": { $lte: 10 } }, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ $or: [{ cuisine: { $nin: ["American ", "Chinese"] } }, { name: /^Wil/ }] }, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({}, { restaurant_id: 1, name: 1, borough: 1, cuisine: 1 })
// query 23
db.restaurants.find({ "address.coord.1": { $gt: 42, $lte: 52 } }, { restaurant_id: 1, name: 1, address: 1 })
db.restaurants.find().sort({ name: 1 })
db.restaurants.find().sort({ name: -1 })
db.restaurants.find({}, { cuisine: 1, borough: 1}).sort({ cuisine: 1, borough: -1 })
db.restaurants.find({ "address.street": null })
db.restaurants.find({ "address.coord": { $type: "double" }})
// query 30
// query 31
// query 32